In [64]:
import numpy as np
n = 30000
np.random.seed(42)

In [65]:
Name = ['stud_'+str(i).zfill(5) for i in range(1,n+1)]
ph = np.random.randint(6666666666,9999999999,n,dtype=np.int64)

email = [i+'@gmail.com' for i in Name]
type = np.random.choice(['INC','PAID'],n)

In [66]:
tenth_per = np.round(np.random.randint(66,99,n)+np.random.rand(n),2)
tenth_YOP = np.random.choice([2020,2019,2018],n)

In [67]:
twelth_per = np.round(np.random.randint(66,99,n)+np.random.rand(n),2)
twelth_YOP = [(i+2).item() for i in tenth_YOP]

In [68]:
print(tenth_YOP)
print(twelth_YOP)

[2018 2018 2019 ... 2020 2020 2018]

In [69]:
stream = np.random.choice(['BCA','BCS','BE','BTECH'],n)

In [70]:
degree_per = np.round(np.random.randint(66,99,n)+np.random.rand(n),2)

In [71]:
degree_YOP = []
for i,year in enumerate(twelth_YOP):
    if stream[i] == "BE" or stream[i] == 'BTECH':
        degree_YOP.append(year+4)
    else:
        degree_YOP.append(year+3)

In [72]:
print(stream)
print(twelth_YOP)
print(degree_YOP)

['BTECH' 'BCS' 'BE' ... 'BCA' 'BCA' 'BCS']

In [73]:
mas_stream = np.random.choice(['MCA','ME','MTECH',None],n)
mas_stream

array(['ME', 'MTECH', 'ME', ..., 'MTECH', 'MCA', 'MTECH'], dtype=object)

In [74]:
mas_per = []
for i in mas_stream:
    if i != None:
        mas_per.append(np.random.randint(37,99))
    else:
        mas_per.append(np.nan)

mas_per = np.array(mas_per)
mas_per.size

30000

In [75]:
mas_yop = []
for i,j in zip(mas_stream,degree_YOP):
    if i!= None:
        mas_yop.append(j+2)
    else:
        mas_yop.append(np.nan)

mas_yop = np.array(mas_yop)
mas_yop.size

30000

In [76]:
course = np.random.choice(['PFD','PDA','PDS','PS'],n)
course

array(['PDA', 'PDA', 'PFD', ..., 'PDS', 'PDA', 'PFD'], dtype='<U3')

In [77]:
status = np.random.choice(['Placed','Not placed'],n)
status

array(['Placed', 'Not placed', 'Placed', ..., 'Not placed', 'Not placed',
       'Not placed'], dtype='<U10')

In [78]:
import pandas as pd

Py_df = pd.DataFrame({
    'Name':Name,
    'Phone Number':ph,
    'Email ID':email,
    'Type':type,
    'course':course,
    'Tenth YOP':tenth_YOP,
    'Tenth Percentage':tenth_per,
    'PUC YOP':twelth_YOP,
    'PUC Percentage':twelth_per,
    'Degree YOP':degree_YOP,
    'Degree Stream':stream,
    'Degree Percentage':degree_per,
    'Masters YOP':mas_yop,
    'Masters Stream': mas_stream,
    'Masters Percentage': mas_per})

In [79]:
Py_df

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
0,stud_00001,8275304208,stud_00001@gmail.com,INC,PDA,2018,77.77,2020,94.73,2024,BTECH,69.51,2026.0,ME,81.0
1,stud_00002,7454513080,stud_00002@gmail.com,INC,PDA,2018,98.66,2020,76.28,2023,BCS,82.94,2025.0,MTECH,46.0
2,stud_00003,9810556692,stud_00003@gmail.com,INC,PFD,2019,87.80,2021,96.03,2025,BE,79.56,2027.0,ME,89.0
3,stud_00004,9237885286,stud_00004@gmail.com,PAID,PFD,2018,74.50,2020,66.61,2024,BTECH,75.49,NaN,None,NaN
4,stud_00005,9230118590,stud_00005@gmail.com,PAID,PFD,2018,72.19,2020,83.58,2023,BCA,97.41,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,stud_29996,7672086862,stud_29996@gmail.com,PAID,PDS,2020,96.74,2022,87.91,2025,BCA,91.52,2027.0,MCA,71.0
29996,stud_29997,9964088345,stud_29997@gmail.com,INC,PS,2018,73.75,2020,66.14,2024,BE,97.64,NaN,None,NaN
29997,stud_29998,7488339500,stud_29998@gmail.com,PAID,PDS,2020,93.89,2022,94.93,2025,BCA,66.44,2027.0,MTECH,41.0
29998,stud_29999,8790538516,stud_29999@gmail.com,INC,PDA,2020,96.54,2022,92.86,2025,BCA,69.26,2027.0,MCA,42.0
29999,stud_30000,7897372031,stud_30000@gmail.com,INC,PFD,2018,78.44,2020,84.96,2023,BCS,70.41,2025.0,MTECH,73.0

In [80]:
Py_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                30000 non-null  object
 1   Phone Number        30000 non-null  int64
 2   Email ID            30000 non-null  object
 3   Type                30000 non-null  object
 4   course              30000 non-null  object
 5   Tenth YOP           30000 non-null  int64
 6   Tenth Percentage    30000 non-null  float64
 7   PUC YOP             30000 non-null  int64
 8   PUC Percentage      30000 non-null  float64
 9   Degree YOP          30000 non-null  int64
 10  Degree Stream       30000 non-null  object
 11  Degree Percentage   30000 non-null  float64
 12  Masters YOP         22552 non-null  float64
 13  Masters Stream      22552 non-null  object
 14  Masters Percentage  22552 non-null  float64
dtypes: float64(5), int64(4), object(6)
memory usage: 3.4+ MB

In [81]:
Py_df.isna().sum()

Name                     0
Phone Number             0
Email ID                 0
Type                     0
course                   0
Tenth YOP                0
Tenth Percentage         0
PUC YOP                  0
PUC Percentage           0
Degree YOP               0
Degree Stream            0
Degree Percentage        0
Masters YOP           7448
Masters Stream        7448
Masters Percentage    7448
dtype: int64

In [82]:
Py_df.columns

Index(['Name', 'Phone Number', 'Email ID', 'Type', 'course', 'Tenth YOP',
       'Tenth Percentage', 'PUC YOP', 'PUC Percentage', 'Degree YOP',
       'Degree Stream', 'Degree Percentage', 'Masters YOP', 'Masters Stream',
       'Masters Percentage'],
      dtype='object')

In [83]:
#first 5 element
Py_df.head()

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
0,stud_00001,8275304208,stud_00001@gmail.com,INC,PDA,2018,77.77,2020,94.73,2024,BTECH,69.51,2026.0,ME,81.0
1,stud_00002,7454513080,stud_00002@gmail.com,INC,PDA,2018,98.66,2020,76.28,2023,BCS,82.94,2025.0,MTECH,46.0
2,stud_00003,9810556692,stud_00003@gmail.com,INC,PFD,2019,87.80,2021,96.03,2025,BE,79.56,2027.0,ME,89.0
3,stud_00004,9237885286,stud_00004@gmail.com,PAID,PFD,2018,74.50,2020,66.61,2024,BTECH,75.49,NaN,None,NaN
4,stud_00005,9230118590,stud_00005@gmail.com,PAID,PFD,2018,72.19,2020,83.58,2023,BCA,97.41,NaN,None,NaN

In [84]:
#last 5 element
Py_df.tail()

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
29995,stud_29996,7672086862,stud_29996@gmail.com,PAID,PDS,2020,96.74,2022,87.91,2025,BCA,91.52,2027.0,MCA,71.0
29996,stud_29997,9964088345,stud_29997@gmail.com,INC,PS,2018,73.75,2020,66.14,2024,BE,97.64,NaN,None,NaN
29997,stud_29998,7488339500,stud_29998@gmail.com,PAID,PDS,2020,93.89,2022,94.93,2025,BCA,66.44,2027.0,MTECH,41.0
29998,stud_29999,8790538516,stud_29999@gmail.com,INC,PDA,2020,96.54,2022,92.86,2025,BCA,69.26,2027.0,MCA,42.0
29999,stud_30000,7897372031,stud_30000@gmail.com,INC,PFD,2018,78.44,2020,84.96,2023,BCS,70.41,2025.0,MTECH,73.0

In [85]:
#information of the dataset
Py_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                30000 non-null  object
 1   Phone Number        30000 non-null  int64
 2   Email ID            30000 non-null  object
 3   Type                30000 non-null  object
 4   course              30000 non-null  object
 5   Tenth YOP           30000 non-null  int64
 6   Tenth Percentage    30000 non-null  float64
 7   PUC YOP             30000 non-null  int64
 8   PUC Percentage      30000 non-null  float64
 9   Degree YOP          30000 non-null  int64
 10  Degree Stream       30000 non-null  object
 11  Degree Percentage   30000 non-null  float64
 12  Masters YOP         22552 non-null  float64
 13  Masters Stream      22552 non-null  object
 14  Masters Percentage  22552 non-null  float64
dtypes: float64(5), int64(4), object(6)
memory usage: 3.4+ MB

In [87]:
#describe
Py_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Phone Number,30000.0,8.335549e+09,9.621247e+08,6.666707e+09,7.502568e+09,8.345045e+09,9.165423e+09,9.999772e+09
Tenth YOP,30000.0,2.019003e+03,8.158913e-01,2.018000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.020000e+03
Tenth Percentage,30000.0,8.259402e+01,9.534354e+00,6.600000e+01,7.433000e+01,8.271500e+01,9.082250e+01,9.900000e+01
PUC YOP,30000.0,2.021003e+03,8.158913e-01,2.020000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2.022000e+03
PUC Percentage,30000.0,8.247193e+01,9.517372e+00,6.600000e+01,7.427000e+01,8.245000e+01,9.074250e+01,9.900000e+01
Degree YOP,30000.0,2.024503e+03,9.595606e-01,2.023000e+03,2.024000e+03,2.025000e+03,2.025000e+03,2.026000e+03
Degree Percentage,30000.0,8.245104e+01,9.527992e+00,6.600000e+01,7.417000e+01,8.247000e+01,9.065000e+01,9.900000e+01
Masters YOP,22552.0,2.026503e+03,9.608507e-01,2.025000e+03,2.026000e+03,2.027000e+03,2.027000e+03,2.028000e+03
Masters Percentage,22552.0,6.747592e+01,1.790705e+01,3.700000e+01,5.200000e+01,6.700000e+01,8.300000e+01,9.800000e+01

In [89]:
#include object datatype in describe
Py_df.describe(include=object).T

                count unique                   top   freq
Name            30000  30000            stud_30000      1
Email ID        30000  30000  stud_30000@gmail.com      1
Type            30000      2                   INC  15005
course          30000      4                    PS   7555
Degree Stream   30000      4                   BCA   7513
Masters Stream  22552      3                   MCA   7523

In [98]:
Py_df.columns

Index(['Name', 'Phone Number', 'Email ID', 'Type', 'course', 'Tenth YOP',
       'Tenth Percentage', 'PUC YOP', 'PUC Percentage', 'Degree YOP',
       'Degree Stream', 'Degree Percentage', 'Masters YOP', 'Masters Stream',
       'Masters Percentage'],
      dtype='object')

In [105]:
#number of unique values per columns

print(Py_df['Email ID'].unique())
print()
print('Number of the unique values:',Py_df['Email ID'].nunique())
print()
print(Py_df['Email ID'].value_counts())

['stud_00001@gmail.com' 'stud_00002@gmail.com' 'stud_00003@gmail.com' ...
 'stud_29998@gmail.com' 'stud_29999@gmail.com' 'stud_30000@gmail.com']

Number of the unique values: 30000

Email ID
stud_30000@gmail.com    1
stud_00001@gmail.com    1
stud_00002@gmail.com    1
stud_00003@gmail.com    1
stud_00004@gmail.com    1
                       ..
stud_00020@gmail.com    1
stud_00021@gmail.com    1
stud_00022@gmail.com    1
stud_00023@gmail.com    1
stud_00024@gmail.com    1
Name: count, Length: 30000, dtype: int64

In [108]:
print('----- Type -----\n')
print(Py_df['Type'].unique())
print()
print('Number of unique elements: ',Py_df['Type'].nunique(),'\n')
print(Py_df['Type'].value_counts())

----- Type -----

['INC' 'PAID']

Number of unique elements:  2

Type
INC     15005
PAID    14995
Name: count, dtype: int64

In [112]:
print('----- course -----\n')
print(Py_df['course'].unique())
print()
print('Number of unique elements: ',Py_df['course'].nunique(),'\n')
print(Py_df['course'].value_counts())

----- course -----

['PDA' 'PFD' 'PS' 'PDS']

Number of unique elements:  4

course
PS     7555
PDS    7530
PFD    7523
PDA    7392
Name: count, dtype: int64

In [111]:
print('----- Tenth YOP -----\n')
print(Py_df['Tenth YOP'].unique())
print()
print('Number of unique elements: ',Py_df['Tenth YOP'].nunique(),'\n')
print(Py_df['Tenth YOP'].value_counts())

----- Tenth YOP -----

[2018 2019 2020]

Number of unique elements:  3

Tenth YOP
2020    10033
2019    10030
2018     9937
Name: count, dtype: int64

In [113]:
print('----- PUC YOP -----\n')
print(Py_df['PUC YOP'].unique())
print()
print('Number of unique elements: ',Py_df['PUC YOP'].nunique(),'\n')
print(Py_df['PUC YOP'].value_counts())

----- PUC YOP -----

[2020 2021 2022]

Number of unique elements:  3

PUC YOP
2022    10033
2021    10030
2020     9937
Name: count, dtype: int64

In [114]:
print('----- Degree YOP -----\n')
print(Py_df['Degree YOP'].unique())
print()
print('Number of unique elements: ',Py_df['Degree YOP'].nunique(),'\n')
print(Py_df['Degree YOP'].value_counts())

----- Degree YOP -----

[2024 2023 2025 2026]

Number of unique elements:  4

Degree YOP
2025    10005
2024     9934
2026     5046
2023     5015
Name: count, dtype: int64

In [115]:
print('----- Degree Stream -----\n')
print(Py_df['Degree Stream'].unique())
print()
print('Number of unique elements: ',Py_df['Degree Stream'].nunique(),'\n')
print(Py_df['Degree Stream'].value_counts())

----- Degree Stream -----

['BTECH' 'BCS' 'BE' 'BCA']

Number of unique elements:  4

Degree Stream
BCA      7513
BCS      7501
BTECH    7497
BE       7489
Name: count, dtype: int64

In [116]:
print('----- Masters YOP -----\n')
print(Py_df['Masters YOP'].unique())
print()
print('Number of unique elements: ',Py_df['Masters YOP'].nunique(),'\n')
print(Py_df['Masters YOP'].value_counts(dropna=False))

----- Masters YOP -----

[2026. 2025. 2027.   nan 2028.]

Number of unique elements:  4

Masters YOP
2027.0    7522
NaN       7448
2026.0    7439
2028.0    3801
2025.0    3790
Name: count, dtype: int64

In [117]:
print('----- Masters Stream -----\n')
print(Py_df['Masters Stream'].unique())
print()
print('Number of unique elements: ',Py_df['Masters Stream'].nunique(),'\n')
print(Py_df['Masters Stream'].value_counts(dropna=False))

----- Masters Stream -----

['ME' 'MTECH' None 'MCA']

Number of unique elements:  3

Masters Stream
MCA      7523
ME       7519
MTECH    7510
None     7448
Name: count, dtype: int64

In [118]:
Py_df.values

array([['stud_00001', 8275304208, 'stud_00001@gmail.com', ..., 2026.0,
        'ME', 81.0],
       ['stud_00002', 7454513080, 'stud_00002@gmail.com', ..., 2025.0,
        'MTECH', 46.0],
       ['stud_00003', 9810556692, 'stud_00003@gmail.com', ..., 2027.0,
        'ME', 89.0],
       ...,
       ['stud_29998', 7488339500, 'stud_29998@gmail.com', ..., 2027.0,
        'MTECH', 41.0],
       ['stud_29999', 8790538516, 'stud_29999@gmail.com', ..., 2027.0,
        'MCA', 42.0],
       ['stud_30000', 7897372031, 'stud_30000@gmail.com', ..., 2025.0,
        'MTECH', 73.0]], dtype=object)

In [119]:
Py_df.index

RangeIndex(start=0, stop=30000, step=1)

In [120]:
#transpose
Py_df.T

,0,1,2,3,4,5,6,7,8,9,...,29990,29991,29992,29993,29994,29995,29996,29997,29998,29999
Name,stud_00001,stud_00002,stud_00003,stud_00004,stud_00005,stud_00006,stud_00007,stud_00008,stud_00009,stud_00010,...,stud_29991,stud_29992,stud_29993,stud_29994,stud_29995,stud_29996,stud_29997,stud_29998,stud_29999,stud_30000
Phone Number,8275304208,7454513080,9810556692,9237885286,9230118590,7336761616,8581503779,7336658044,7096055680,6916133876,...,6805138015,7572118413,9895219203,7093269180,9481870437,7672086862,9964088345,7488339500,8790538516,7897372031
Email ID,stud_00001@gmail.com,stud_00002@gmail.com,stud_00003@gmail.com,stud_00004@gmail.com,stud_00005@gmail.com,stud_00006@gmail.com,stud_00007@gmail.com,stud_00008@gmail.com,stud_00009@gmail.com,stud_00010@gmail.com,...,stud_29991@gmail.com,stud_29992@gmail.com,stud_29993@gmail.com,stud_29994@gmail.com,stud_29995@gmail.com,stud_29996@gmail.com,stud_29997@gmail.com,stud_29998@gmail.com,stud_29999@gmail.com,stud_30000@gmail.com
Type,INC,INC,INC,PAID,PAID,PAID,PAID,PAID,INC,INC,...,INC,PAID,INC,INC,PAID,PAID,INC,PAID,INC,INC
course,PDA,PDA,PFD,PFD,PFD,PFD,PS,PFD,PS,PDA,...,PDS,PDS,PS,PDA,PDA,PDS,PS,PDS,PDA,PFD
Tenth YOP,2018,2018,2019,2018,2018,2020,2020,2018,2019,2020,...,2020,2020,2020,2018,2018,2020,2018,2020,2020,2018
Tenth Percentage,77.77,98.66,87.8,74.5,72.19,82.48,75.31,90.69,92.14,95.33,...,78.37,71.72,94.58,67.34,75.41,96.74,73.75,93.89,96.54,78.44
PUC YOP,2020,2020,2021,2020,2020,2022,2022,2020,2021,2022,...,2022,2022,2022,2020,2020,2022,2020,2022,2022,2020
PUC Percentage,94.73,76.28,96.03,66.61,83.58,67.87,66.17,90.95,68.05,89.57,...,84.75,67.87,79.21,69.05,72.52,87.91,66.14,94.93,92.86,84.96
Degree YOP,2024,2023,2025,2024,2023,2025,2026,2023,2024,2026,...,2025,2025,2026,2024,2023,2025,2024,2025,2025,2023
Degree Stream,BTECH,BCS,BE,BTECH,BCA,BCA,BE,BCA,BCS,BTECH,...,BCS,BCS,BTECH,BTECH,BCS,BCA,BE,BCA,BCA,BCS
Degree Percentage,69.51,82.94,79.56,75.49,97.41,86.77,86.59,81.91,75.83,86.75,...,74.67,67.52,83.79,77.52,93.59,91.52,97.64,66.44,69.26,70.41
Masters YOP,2026.0,2025.0,2027.0,NaN,NaN,2027.0,2028.0,2025.0,2026.0,NaN,...,2027.0,2027.0,2028.0,2026.0,NaN,2027.0,NaN,2027.0,2027.0,2025.0
Masters Stream,ME,MTECH,ME,None,None,MTECH,MCA,MCA,ME,None,...,MCA,MTECH,ME,MCA,None,MCA,None,MTECH,MCA,MTECH
Masters Percentage,81.0,46.0,89.0,NaN,NaN,56.0,83.0,75.0,53.0,NaN,...,76.0,82.0,66.0,82.0,NaN,71.0,NaN,41.0,42.0,73.0

In [121]:
#all columns
Py_df.columns

Index(['Name', 'Phone Number', 'Email ID', 'Type', 'course', 'Tenth YOP',
       'Tenth Percentage', 'PUC YOP', 'PUC Percentage', 'Degree YOP',
       'Degree Stream', 'Degree Percentage', 'Masters YOP', 'Masters Stream',
       'Masters Percentage'],
      dtype='object')

In [ ]:
#taking random samples

Py_df.sample() # by default it return only one row

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
3955,stud_03956,7047221009,stud_03956@gmail.com,PAID,PDS,2019,75.19,2021,92.32,2024,BCA,66.11,2026.0,ME,78.0

In [ ]:
Py_df.sample(5) #returnn 5 random rows

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
28930,stud_28931,7935702138,stud_28931@gmail.com,INC,PFD,2019,88.38,2021,82.84,2025,BE,70.57,2027.0,ME,58.0
25249,stud_25250,6830440688,stud_25250@gmail.com,INC,PFD,2018,81.45,2020,95.71,2024,BE,90.60,2026.0,ME,81.0
2755,stud_02756,9465742587,stud_02756@gmail.com,PAID,PDS,2018,74.33,2020,72.09,2023,BCA,96.52,2025.0,ME,61.0
10214,stud_10215,8239854724,stud_10215@gmail.com,INC,PDS,2019,68.07,2021,71.40,2024,BCA,87.47,NaN,None,NaN
1215,stud_01216,9759200043,stud_01216@gmail.com,PAID,PS,2018,80.88,2020,96.91,2024,BE,91.05,2026.0,ME,44.0

In [128]:
Py_df.sample(frac=0.25)   # return the 25% of the data

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
28061,stud_28062,7975498690,stud_28062@gmail.com,INC,PFD,2019,66.85,2021,97.60,2024,BCA,92.78,NaN,None,NaN
5438,stud_05439,7897258753,stud_05439@gmail.com,PAID,PDA,2019,67.94,2021,91.96,2025,BE,94.87,2027.0,ME,89.0
17517,stud_17518,7948201220,stud_17518@gmail.com,PAID,PDA,2020,72.73,2022,91.05,2026,BE,97.78,NaN,None,NaN
22921,stud_22922,8004302128,stud_22922@gmail.com,INC,PDS,2018,74.67,2020,96.73,2023,BCS,72.88,2025.0,ME,49.0
24673,stud_24674,7657234925,stud_24674@gmail.com,INC,PFD,2018,67.10,2020,78.49,2023,BCA,87.71,2025.0,ME,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4342,stud_04343,7607769077,stud_04343@gmail.com,PAID,PDA,2018,78.74,2020,66.41,2024,BE,88.40,2026.0,ME,88.0
19169,stud_19170,9605324814,stud_19170@gmail.com,INC,PFD,2020,97.38,2022,85.67,2025,BCS,90.56,2027.0,MTECH,92.0
19300,stud_19301,8432874730,stud_19301@gmail.com,PAID,PDA,2020,80.54,2022,78.73,2026,BE,80.41,2028.0,MCA,43.0
11140,stud_11141,7981768137,stud_11141@gmail.com,INC,PDA,2018,70.60,2020,79.33,2023,BCA,70.65,2025.0,MTECH,97.0
19326,stud_19327,9632507195,stud_19327@gmail.com,INC,PS,2018,89.52,2020,70.11,2023,BCA,89.25,2025.0,ME,46.0

In [135]:
#sort values by columns

Py_df.sort_values(by='Tenth Percentage')    #going to sort using the given columnn default asending order

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
26324,stud_26325,7512522548,stud_26325@gmail.com,INC,PFD,2018,66.00,2020,86.40,2023,BCS,72.33,2025.0,MCA,53.0
16340,stud_16341,7750432944,stud_16341@gmail.com,PAID,PDA,2019,66.00,2021,73.89,2025,BE,78.20,2027.0,MTECH,70.0
10089,stud_10090,9904076429,stud_10090@gmail.com,INC,PS,2019,66.01,2021,89.75,2025,BTECH,66.29,NaN,None,NaN
2842,stud_02843,8944296995,stud_02843@gmail.com,PAID,PDS,2020,66.01,2022,91.45,2025,BCA,81.55,NaN,None,NaN
11715,stud_11716,6908824876,stud_11716@gmail.com,PAID,PDS,2019,66.01,2021,68.15,2025,BTECH,72.27,2027.0,MCA,97.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,stud_00969,9322050691,stud_00969@gmail.com,PAID,PFD,2019,98.99,2021,96.07,2025,BE,69.96,NaN,None,NaN
8656,stud_08657,9288211851,stud_08657@gmail.com,PAID,PDA,2019,98.99,2021,87.37,2025,BTECH,71.84,2027.0,MTECH,68.0
12686,stud_12687,9033800679,stud_12687@gmail.com,INC,PDS,2019,98.99,2021,81.21,2025,BTECH,95.97,2027.0,MCA,71.0
21956,stud_21957,7941010479,stud_21957@gmail.com,PAID,PDS,2019,99.00,2021,72.16,2024,BCS,90.84,NaN,None,NaN
12221,stud_12222,6955462988,stud_12222@gmail.com,PAID,PS,2018,99.00,2020,82.28,2023,BCS,79.05,2025.0,MTECH,55.0

In [133]:
#by using multiple columns

Py_df.sort_values(by=['Tenth YOP','Tenth Percentage'])

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
26324,stud_26325,7512522548,stud_26325@gmail.com,INC,PFD,2018,66.00,2020,86.40,2023,BCS,72.33,2025.0,MCA,53.0
14676,stud_14677,9548481122,stud_14677@gmail.com,INC,PDA,2018,66.01,2020,88.71,2024,BE,88.12,2026.0,ME,80.0
16071,stud_16072,7216207468,stud_16072@gmail.com,INC,PFD,2018,66.02,2020,76.03,2023,BCS,93.70,2025.0,ME,70.0
18104,stud_18105,8323307326,stud_18105@gmail.com,INC,PFD,2018,66.02,2020,67.66,2024,BE,76.89,NaN,None,NaN
22298,stud_22299,9167929165,stud_22299@gmail.com,INC,PS,2018,66.02,2020,66.70,2024,BE,91.90,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28788,stud_28789,9990803009,stud_28789@gmail.com,PAID,PDS,2020,98.98,2022,96.55,2026,BTECH,87.30,2028.0,MTECH,39.0
1878,stud_01879,7948175092,stud_01879@gmail.com,PAID,PS,2020,98.99,2022,70.06,2025,BCA,72.26,2027.0,ME,54.0
4695,stud_04696,7548859015,stud_04696@gmail.com,INC,PS,2020,98.99,2022,93.78,2026,BE,83.10,NaN,None,NaN
10362,stud_10363,9611780568,stud_10363@gmail.com,INC,PDS,2020,98.99,2022,89.02,2025,BCA,85.03,2027.0,MCA,54.0
21245,stud_21246,9755592363,stud_21246@gmail.com,INC,PDA,2020,98.99,2022,70.71,2025,BCA,93.39,2027.0,ME,67.0

In [134]:
#by desending order
Py_df.sort_values(by='Tenth Percentage',ascending=False)

,Name,Phone Number,Email ID,Type,course,Tenth YOP,Tenth Percentage,PUC YOP,PUC Percentage,Degree YOP,Degree Stream,Degree Percentage,Masters YOP,Masters Stream,Masters Percentage
12221,stud_12222,6955462988,stud_12222@gmail.com,PAID,PS,2018,99.00,2020,82.28,2023,BCS,79.05,2025.0,MTECH,55.0
21956,stud_21957,7941010479,stud_21957@gmail.com,PAID,PDS,2019,99.00,2021,72.16,2024,BCS,90.84,NaN,None,NaN
10362,stud_10363,9611780568,stud_10363@gmail.com,INC,PDS,2020,98.99,2022,89.02,2025,BCA,85.03,2027.0,MCA,54.0
8656,stud_08657,9288211851,stud_08657@gmail.com,PAID,PDA,2019,98.99,2021,87.37,2025,BTECH,71.84,2027.0,MTECH,68.0
21245,stud_21246,9755592363,stud_21246@gmail.com,INC,PDA,2020,98.99,2022,70.71,2025,BCA,93.39,2027.0,ME,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10089,stud_10090,9904076429,stud_10090@gmail.com,INC,PS,2019,66.01,2021,89.75,2025,BTECH,66.29,NaN,None,NaN
2842,stud_02843,8944296995,stud_02843@gmail.com,PAID,PDS,2020,66.01,2022,91.45,2025,BCA,81.55,NaN,None,NaN
11715,stud_11716,6908824876,stud_11716@gmail.com,PAID,PDS,2019,66.01,2021,68.15,2025,BTECH,72.27,2027.0,MCA,97.0
26324,stud_26325,7512522548,stud_26325@gmail.com,INC,PFD,2018,66.00,2020,86.40,2023,BCS,72.33,2025.0,MCA,53.0
16340,stud_16341,7750432944,stud_16341@gmail.com,PAID,PDA,2019,66.00,2021,73.89,2025,BE,78.20,2027.0,MTECH,70.0

In [136]:
#sorting by index